name: CICD

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Checkout resonate-sdk-ts repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: npm install

      - name: Run linter and format check
        run: npm run check

      - name: Run type check
        run: npm run type-check

      - name: Run tests
        run: npm test -- --verbose

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Checkout resonate-sdk-ts repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # - name: Publish
      #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      #   run: |
      #     # Use 0.0.0 so as to not conflict with a newer version
      #     # Use the commit sha as a unique identifier
      #     npm version 0.0.0-SNAPSHOT-$GITHUB_SHA --git-tag-version false

      #     # Publish to the main tag
      #     npm publish --provenance --access public --tag main
