name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to release from"
        required: true
        type: string
      tag:
        description: "Git tag (e.g. v1.0.0)"
        required: true
        type: string
      version:
        description: "Package version (e.g. 1.0.0)"
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Verify tag matches package.json version
        if: github.event_name == 'release'
        run: |
          RELEASE_VERSION=${{ github.ref_name }}
          PACKAGE_VERSION=$(npm pkg get version | sed 's/"//g')

          if [ "$RELEASE_VERSION" != "v$PACKAGE_VERSION" ]; then
            echo "Error: GitHub release tag ($RELEASE_VERSION) does not match package.json version ($PACKAGE_VERSION)"
            exit 1
          fi

      - name: Override package.json version
        if: github.event_name == 'workflow_dispatch'
        run: npm pkg set version=${{ github.event.inputs.version }}

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish
        run: |
          NPM_TAG=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || 'latest' }}
          npm publish --provenance --access public --tag ${NPM_TAG}

  verify:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Verify can install package
        run: |
          INSTALL_VERSION=${{ github.event.inputs.tag || github.ref_name }}
          npm install @resonatehq/sdk@${INSTALL_VERSION}
