version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    # reviewers:
    #   - "YOUR_USERNAME"
    # assignees:
    #   - "YOUR_USERNAME"
    # open-pull-requests-limit: 5

    #  Optional: Group updates together to avoid opening too many PRs at once
    # groups:
    #   all-dependencies:
    #     patterns: ["*"]
