// Package schedules provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package schedules

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// PromiseValue defines model for PromiseValue.
type PromiseValue struct {
	Data    *string           `json:"data,omitempty"`
	Headers map[string]string `json:"headers"`
}

// Schedule defines model for Schedule.
type Schedule struct {
	CreatedOn      *int64             `json:"createdOn,omitempty"`
	Cron           string             `json:"cron"`
	Description    *string            `json:"description,omitempty"`
	Id             string             `json:"id"`
	IdempotencyKey *string            `json:"idempotencyKey,omitempty"`
	LastRunTime    *int64             `json:"lastRunTime,omitempty"`
	NextRunTime    *int64             `json:"nextRunTime,omitempty"`
	PromiseId      string             `json:"promiseId"`
	PromiseParam   *PromiseValue      `json:"promiseParam,omitempty"`
	PromiseTags    *map[string]string `json:"promiseTags,omitempty"`
	PromiseTimeout int64              `json:"promiseTimeout"`
	Tags           *map[string]string `json:"tags,omitempty"`
}

// SearchSchedulesResp defines model for SearchSchedulesResp.
type SearchSchedulesResp struct {
	Cursor    *string     `json:"cursor,omitempty"`
	Schedules *[]Schedule `json:"schedules,omitempty"`
}

// IdPath defines model for IdPath.
type IdPath = string

// IdempotencyKeyHeader defines model for IdempotencyKeyHeader.
type IdempotencyKeyHeader = string

// RequestIdHeader defines model for RequestIdHeader.
type RequestIdHeader = string

// SearchSchedulesParams defines parameters for SearchSchedules.
type SearchSchedulesParams struct {
	// Id Search schedules for matching IDs, can include wildcards.
	//
	// For example:
	// - "foo/*" matches all IDs starting with "foo/"
	// - "*/bar" matches all IDs starting with "bar/"
	// - "foo/*/bar" matches all IDs starting with "foo/" and ending with "/bar"
	Id   *string            `form:"id,omitempty" json:"id,omitempty"`
	Tags *map[string]string `json:"tags,omitempty"`

	// Limit Number of results
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Cursor for pagination
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// RequestId Unique ID for each request
	RequestId *RequestIdHeader `json:"request-id,omitempty"`
}

// PostSchedulesParams defines parameters for PostSchedules.
type PostSchedulesParams struct {
	// RequestId Unique ID for each request
	RequestId *RequestIdHeader `json:"request-id,omitempty"`

	// IdempotencyKey Deduplicates multiple requests
	IdempotencyKey *IdempotencyKeyHeader `json:"idempotency-key,omitempty"`
}

// DeleteSchedulesIdParams defines parameters for DeleteSchedulesId.
type DeleteSchedulesIdParams struct {
	// RequestId Unique ID for each request
	RequestId *RequestIdHeader `json:"request-id,omitempty"`
}

// GetSchedulesIdParams defines parameters for GetSchedulesId.
type GetSchedulesIdParams struct {
	// RequestId Unique ID for each request
	RequestId *RequestIdHeader `json:"request-id,omitempty"`
}

// PostSchedulesJSONRequestBody defines body for PostSchedules for application/json ContentType.
type PostSchedulesJSONRequestBody = Schedule

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// SearchSchedules request
	SearchSchedules(ctx context.Context, params *SearchSchedulesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSchedulesWithBody request with any body
	PostSchedulesWithBody(ctx context.Context, params *PostSchedulesParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostSchedules(ctx context.Context, params *PostSchedulesParams, body PostSchedulesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteSchedulesId request
	DeleteSchedulesId(ctx context.Context, id IdPath, params *DeleteSchedulesIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSchedulesId request
	GetSchedulesId(ctx context.Context, id IdPath, params *GetSchedulesIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) SearchSchedules(ctx context.Context, params *SearchSchedulesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchSchedulesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSchedulesWithBody(ctx context.Context, params *PostSchedulesParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSchedulesRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSchedules(ctx context.Context, params *PostSchedulesParams, body PostSchedulesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSchedulesRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteSchedulesId(ctx context.Context, id IdPath, params *DeleteSchedulesIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteSchedulesIdRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSchedulesId(ctx context.Context, id IdPath, params *GetSchedulesIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSchedulesIdRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewSearchSchedulesRequest generates requests for SearchSchedules
func NewSearchSchedulesRequest(server string, params *SearchSchedulesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/schedules")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Id != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "id", runtime.ParamLocationQuery, *params.Id); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Tags != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("deepObject", true, "tags", runtime.ParamLocationQuery, *params.Tags); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cursor", runtime.ParamLocationQuery, *params.Cursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.RequestId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "request-id", runtime.ParamLocationHeader, *params.RequestId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("request-id", headerParam0)
		}

	}

	return req, nil
}

// NewPostSchedulesRequest calls the generic PostSchedules builder with application/json body
func NewPostSchedulesRequest(server string, params *PostSchedulesParams, body PostSchedulesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostSchedulesRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostSchedulesRequestWithBody generates requests for PostSchedules with any type of body
func NewPostSchedulesRequestWithBody(server string, params *PostSchedulesParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/schedules")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.RequestId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "request-id", runtime.ParamLocationHeader, *params.RequestId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("request-id", headerParam0)
		}

		if params.IdempotencyKey != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithLocation("simple", false, "idempotency-key", runtime.ParamLocationHeader, *params.IdempotencyKey)
			if err != nil {
				return nil, err
			}

			req.Header.Set("idempotency-key", headerParam1)
		}

	}

	return req, nil
}

// NewDeleteSchedulesIdRequest generates requests for DeleteSchedulesId
func NewDeleteSchedulesIdRequest(server string, id IdPath, params *DeleteSchedulesIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/schedules/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.RequestId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "request-id", runtime.ParamLocationHeader, *params.RequestId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("request-id", headerParam0)
		}

	}

	return req, nil
}

// NewGetSchedulesIdRequest generates requests for GetSchedulesId
func NewGetSchedulesIdRequest(server string, id IdPath, params *GetSchedulesIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/schedules/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.RequestId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "request-id", runtime.ParamLocationHeader, *params.RequestId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("request-id", headerParam0)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// SearchSchedulesWithResponse request
	SearchSchedulesWithResponse(ctx context.Context, params *SearchSchedulesParams, reqEditors ...RequestEditorFn) (*SearchSchedulesResponse, error)

	// PostSchedulesWithBodyWithResponse request with any body
	PostSchedulesWithBodyWithResponse(ctx context.Context, params *PostSchedulesParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSchedulesResponse, error)

	PostSchedulesWithResponse(ctx context.Context, params *PostSchedulesParams, body PostSchedulesJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSchedulesResponse, error)

	// DeleteSchedulesIdWithResponse request
	DeleteSchedulesIdWithResponse(ctx context.Context, id IdPath, params *DeleteSchedulesIdParams, reqEditors ...RequestEditorFn) (*DeleteSchedulesIdResponse, error)

	// GetSchedulesIdWithResponse request
	GetSchedulesIdWithResponse(ctx context.Context, id IdPath, params *GetSchedulesIdParams, reqEditors ...RequestEditorFn) (*GetSchedulesIdResponse, error)
}

type SearchSchedulesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SearchSchedulesResp
}

// Status returns HTTPResponse.Status
func (r SearchSchedulesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchSchedulesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostSchedulesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Schedule
	JSON201      *Schedule
}

// Status returns HTTPResponse.Status
func (r PostSchedulesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSchedulesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteSchedulesIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteSchedulesIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteSchedulesIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSchedulesIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Schedule
}

// Status returns HTTPResponse.Status
func (r GetSchedulesIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSchedulesIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// SearchSchedulesWithResponse request returning *SearchSchedulesResponse
func (c *ClientWithResponses) SearchSchedulesWithResponse(ctx context.Context, params *SearchSchedulesParams, reqEditors ...RequestEditorFn) (*SearchSchedulesResponse, error) {
	rsp, err := c.SearchSchedules(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchSchedulesResponse(rsp)
}

// PostSchedulesWithBodyWithResponse request with arbitrary body returning *PostSchedulesResponse
func (c *ClientWithResponses) PostSchedulesWithBodyWithResponse(ctx context.Context, params *PostSchedulesParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSchedulesResponse, error) {
	rsp, err := c.PostSchedulesWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSchedulesResponse(rsp)
}

func (c *ClientWithResponses) PostSchedulesWithResponse(ctx context.Context, params *PostSchedulesParams, body PostSchedulesJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSchedulesResponse, error) {
	rsp, err := c.PostSchedules(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSchedulesResponse(rsp)
}

// DeleteSchedulesIdWithResponse request returning *DeleteSchedulesIdResponse
func (c *ClientWithResponses) DeleteSchedulesIdWithResponse(ctx context.Context, id IdPath, params *DeleteSchedulesIdParams, reqEditors ...RequestEditorFn) (*DeleteSchedulesIdResponse, error) {
	rsp, err := c.DeleteSchedulesId(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteSchedulesIdResponse(rsp)
}

// GetSchedulesIdWithResponse request returning *GetSchedulesIdResponse
func (c *ClientWithResponses) GetSchedulesIdWithResponse(ctx context.Context, id IdPath, params *GetSchedulesIdParams, reqEditors ...RequestEditorFn) (*GetSchedulesIdResponse, error) {
	rsp, err := c.GetSchedulesId(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSchedulesIdResponse(rsp)
}

// ParseSearchSchedulesResponse parses an HTTP response from a SearchSchedulesWithResponse call
func ParseSearchSchedulesResponse(rsp *http.Response) (*SearchSchedulesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchSchedulesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SearchSchedulesResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostSchedulesResponse parses an HTTP response from a PostSchedulesWithResponse call
func ParsePostSchedulesResponse(rsp *http.Response) (*PostSchedulesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSchedulesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Schedule
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Schedule
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseDeleteSchedulesIdResponse parses an HTTP response from a DeleteSchedulesIdWithResponse call
func ParseDeleteSchedulesIdResponse(rsp *http.Response) (*DeleteSchedulesIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteSchedulesIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetSchedulesIdResponse parses an HTTP response from a GetSchedulesIdWithResponse call
func ParseGetSchedulesIdResponse(rsp *http.Response) (*GetSchedulesIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSchedulesIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Schedule
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
