// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: internal/app/subsystems/api/grpc/pb/callback.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Callbacks_CreateCallback_FullMethodName = "/callback.Callbacks/CreateCallback"
)

// CallbacksClient is the client API for Callbacks service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CallbacksClient interface {
	CreateCallback(ctx context.Context, in *CreateCallbackRequest, opts ...grpc.CallOption) (*CreateCallbackResponse, error)
}

type callbacksClient struct {
	cc grpc.ClientConnInterface
}

func NewCallbacksClient(cc grpc.ClientConnInterface) CallbacksClient {
	return &callbacksClient{cc}
}

func (c *callbacksClient) CreateCallback(ctx context.Context, in *CreateCallbackRequest, opts ...grpc.CallOption) (*CreateCallbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCallbackResponse)
	err := c.cc.Invoke(ctx, Callbacks_CreateCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallbacksServer is the server API for Callbacks service.
// All implementations must embed UnimplementedCallbacksServer
// for forward compatibility.
type CallbacksServer interface {
	CreateCallback(context.Context, *CreateCallbackRequest) (*CreateCallbackResponse, error)
	mustEmbedUnimplementedCallbacksServer()
}

// UnimplementedCallbacksServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCallbacksServer struct{}

func (UnimplementedCallbacksServer) CreateCallback(context.Context, *CreateCallbackRequest) (*CreateCallbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCallback not implemented")
}
func (UnimplementedCallbacksServer) mustEmbedUnimplementedCallbacksServer() {}
func (UnimplementedCallbacksServer) testEmbeddedByValue()                   {}

// UnsafeCallbacksServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallbacksServer will
// result in compilation errors.
type UnsafeCallbacksServer interface {
	mustEmbedUnimplementedCallbacksServer()
}

func RegisterCallbacksServer(s grpc.ServiceRegistrar, srv CallbacksServer) {
	// If the following call pancis, it indicates UnimplementedCallbacksServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Callbacks_ServiceDesc, srv)
}

func _Callbacks_CreateCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallbacksServer).CreateCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Callbacks_CreateCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallbacksServer).CreateCallback(ctx, req.(*CreateCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Callbacks_ServiceDesc is the grpc.ServiceDesc for Callbacks service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Callbacks_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "callback.Callbacks",
	HandlerType: (*CallbacksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCallback",
			Handler:    _Callbacks_CreateCallback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/app/subsystems/api/grpc/pb/callback.proto",
}
