// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: internal/app/subsystems/api/grpc/pb/lock.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Locks_AcquireLock_FullMethodName    = "/lock.Locks/AcquireLock"
	Locks_ReleaseLock_FullMethodName    = "/lock.Locks/ReleaseLock"
	Locks_HeartbeatLocks_FullMethodName = "/lock.Locks/HeartbeatLocks"
)

// LocksClient is the client API for Locks service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LocksClient interface {
	AcquireLock(ctx context.Context, in *AcquireLockRequest, opts ...grpc.CallOption) (*AcquireLockResponse, error)
	ReleaseLock(ctx context.Context, in *ReleaseLockRequest, opts ...grpc.CallOption) (*ReleaseLockResponse, error)
	HeartbeatLocks(ctx context.Context, in *HeartbeatLocksRequest, opts ...grpc.CallOption) (*HeartbeatLocksResponse, error)
}

type locksClient struct {
	cc grpc.ClientConnInterface
}

func NewLocksClient(cc grpc.ClientConnInterface) LocksClient {
	return &locksClient{cc}
}

func (c *locksClient) AcquireLock(ctx context.Context, in *AcquireLockRequest, opts ...grpc.CallOption) (*AcquireLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireLockResponse)
	err := c.cc.Invoke(ctx, Locks_AcquireLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locksClient) ReleaseLock(ctx context.Context, in *ReleaseLockRequest, opts ...grpc.CallOption) (*ReleaseLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseLockResponse)
	err := c.cc.Invoke(ctx, Locks_ReleaseLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locksClient) HeartbeatLocks(ctx context.Context, in *HeartbeatLocksRequest, opts ...grpc.CallOption) (*HeartbeatLocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatLocksResponse)
	err := c.cc.Invoke(ctx, Locks_HeartbeatLocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocksServer is the server API for Locks service.
// All implementations must embed UnimplementedLocksServer
// for forward compatibility.
type LocksServer interface {
	AcquireLock(context.Context, *AcquireLockRequest) (*AcquireLockResponse, error)
	ReleaseLock(context.Context, *ReleaseLockRequest) (*ReleaseLockResponse, error)
	HeartbeatLocks(context.Context, *HeartbeatLocksRequest) (*HeartbeatLocksResponse, error)
	mustEmbedUnimplementedLocksServer()
}

// UnimplementedLocksServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocksServer struct{}

func (UnimplementedLocksServer) AcquireLock(context.Context, *AcquireLockRequest) (*AcquireLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcquireLock not implemented")
}
func (UnimplementedLocksServer) ReleaseLock(context.Context, *ReleaseLockRequest) (*ReleaseLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseLock not implemented")
}
func (UnimplementedLocksServer) HeartbeatLocks(context.Context, *HeartbeatLocksRequest) (*HeartbeatLocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartbeatLocks not implemented")
}
func (UnimplementedLocksServer) mustEmbedUnimplementedLocksServer() {}
func (UnimplementedLocksServer) testEmbeddedByValue()               {}

// UnsafeLocksServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocksServer will
// result in compilation errors.
type UnsafeLocksServer interface {
	mustEmbedUnimplementedLocksServer()
}

func RegisterLocksServer(s grpc.ServiceRegistrar, srv LocksServer) {
	// If the following call pancis, it indicates UnimplementedLocksServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Locks_ServiceDesc, srv)
}

func _Locks_AcquireLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocksServer).AcquireLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Locks_AcquireLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocksServer).AcquireLock(ctx, req.(*AcquireLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Locks_ReleaseLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocksServer).ReleaseLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Locks_ReleaseLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocksServer).ReleaseLock(ctx, req.(*ReleaseLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Locks_HeartbeatLocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatLocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocksServer).HeartbeatLocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Locks_HeartbeatLocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocksServer).HeartbeatLocks(ctx, req.(*HeartbeatLocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Locks_ServiceDesc is the grpc.ServiceDesc for Locks service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Locks_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lock.Locks",
	HandlerType: (*LocksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcquireLock",
			Handler:    _Locks_AcquireLock_Handler,
		},
		{
			MethodName: "ReleaseLock",
			Handler:    _Locks_ReleaseLock_Handler,
		},
		{
			MethodName: "HeartbeatLocks",
			Handler:    _Locks_HeartbeatLocks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/app/subsystems/api/grpc/pb/lock.proto",
}
