// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: internal/app/subsystems/api/grpc/pb/promise.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Promises_ReadPromise_FullMethodName          = "/promise.Promises/ReadPromise"
	Promises_SearchPromises_FullMethodName       = "/promise.Promises/SearchPromises"
	Promises_CreatePromise_FullMethodName        = "/promise.Promises/CreatePromise"
	Promises_CreatePromiseAndTask_FullMethodName = "/promise.Promises/CreatePromiseAndTask"
	Promises_ResolvePromise_FullMethodName       = "/promise.Promises/ResolvePromise"
	Promises_RejectPromise_FullMethodName        = "/promise.Promises/RejectPromise"
	Promises_CancelPromise_FullMethodName        = "/promise.Promises/CancelPromise"
	Promises_CreateCallback_FullMethodName       = "/promise.Promises/CreateCallback"
	Promises_CreateSubscription_FullMethodName   = "/promise.Promises/CreateSubscription"
)

// PromisesClient is the client API for Promises service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PromisesClient interface {
	ReadPromise(ctx context.Context, in *ReadPromiseRequest, opts ...grpc.CallOption) (*ReadPromiseResponse, error)
	SearchPromises(ctx context.Context, in *SearchPromisesRequest, opts ...grpc.CallOption) (*SearchPromisesResponse, error)
	CreatePromise(ctx context.Context, in *CreatePromiseRequest, opts ...grpc.CallOption) (*CreatePromiseResponse, error)
	CreatePromiseAndTask(ctx context.Context, in *CreatePromiseAndTaskRequest, opts ...grpc.CallOption) (*CreatePromiseAndTaskResponse, error)
	ResolvePromise(ctx context.Context, in *ResolvePromiseRequest, opts ...grpc.CallOption) (*ResolvePromiseResponse, error)
	RejectPromise(ctx context.Context, in *RejectPromiseRequest, opts ...grpc.CallOption) (*RejectPromiseResponse, error)
	CancelPromise(ctx context.Context, in *CancelPromiseRequest, opts ...grpc.CallOption) (*CancelPromiseResponse, error)
	CreateCallback(ctx context.Context, in *CreateCallbackRequest, opts ...grpc.CallOption) (*CreateCallbackResponse, error)
	CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*CreateSubscriptionResponse, error)
}

type promisesClient struct {
	cc grpc.ClientConnInterface
}

func NewPromisesClient(cc grpc.ClientConnInterface) PromisesClient {
	return &promisesClient{cc}
}

func (c *promisesClient) ReadPromise(ctx context.Context, in *ReadPromiseRequest, opts ...grpc.CallOption) (*ReadPromiseResponse, error) {
	out := new(ReadPromiseResponse)
	err := c.cc.Invoke(ctx, Promises_ReadPromise_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promisesClient) SearchPromises(ctx context.Context, in *SearchPromisesRequest, opts ...grpc.CallOption) (*SearchPromisesResponse, error) {
	out := new(SearchPromisesResponse)
	err := c.cc.Invoke(ctx, Promises_SearchPromises_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promisesClient) CreatePromise(ctx context.Context, in *CreatePromiseRequest, opts ...grpc.CallOption) (*CreatePromiseResponse, error) {
	out := new(CreatePromiseResponse)
	err := c.cc.Invoke(ctx, Promises_CreatePromise_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promisesClient) CreatePromiseAndTask(ctx context.Context, in *CreatePromiseAndTaskRequest, opts ...grpc.CallOption) (*CreatePromiseAndTaskResponse, error) {
	out := new(CreatePromiseAndTaskResponse)
	err := c.cc.Invoke(ctx, Promises_CreatePromiseAndTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promisesClient) ResolvePromise(ctx context.Context, in *ResolvePromiseRequest, opts ...grpc.CallOption) (*ResolvePromiseResponse, error) {
	out := new(ResolvePromiseResponse)
	err := c.cc.Invoke(ctx, Promises_ResolvePromise_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promisesClient) RejectPromise(ctx context.Context, in *RejectPromiseRequest, opts ...grpc.CallOption) (*RejectPromiseResponse, error) {
	out := new(RejectPromiseResponse)
	err := c.cc.Invoke(ctx, Promises_RejectPromise_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promisesClient) CancelPromise(ctx context.Context, in *CancelPromiseRequest, opts ...grpc.CallOption) (*CancelPromiseResponse, error) {
	out := new(CancelPromiseResponse)
	err := c.cc.Invoke(ctx, Promises_CancelPromise_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promisesClient) CreateCallback(ctx context.Context, in *CreateCallbackRequest, opts ...grpc.CallOption) (*CreateCallbackResponse, error) {
	out := new(CreateCallbackResponse)
	err := c.cc.Invoke(ctx, Promises_CreateCallback_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promisesClient) CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*CreateSubscriptionResponse, error) {
	out := new(CreateSubscriptionResponse)
	err := c.cc.Invoke(ctx, Promises_CreateSubscription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromisesServer is the server API for Promises service.
// All implementations must embed UnimplementedPromisesServer
// for forward compatibility
type PromisesServer interface {
	ReadPromise(context.Context, *ReadPromiseRequest) (*ReadPromiseResponse, error)
	SearchPromises(context.Context, *SearchPromisesRequest) (*SearchPromisesResponse, error)
	CreatePromise(context.Context, *CreatePromiseRequest) (*CreatePromiseResponse, error)
	CreatePromiseAndTask(context.Context, *CreatePromiseAndTaskRequest) (*CreatePromiseAndTaskResponse, error)
	ResolvePromise(context.Context, *ResolvePromiseRequest) (*ResolvePromiseResponse, error)
	RejectPromise(context.Context, *RejectPromiseRequest) (*RejectPromiseResponse, error)
	CancelPromise(context.Context, *CancelPromiseRequest) (*CancelPromiseResponse, error)
	CreateCallback(context.Context, *CreateCallbackRequest) (*CreateCallbackResponse, error)
	CreateSubscription(context.Context, *CreateSubscriptionRequest) (*CreateSubscriptionResponse, error)
	mustEmbedUnimplementedPromisesServer()
}

// UnimplementedPromisesServer must be embedded to have forward compatible implementations.
type UnimplementedPromisesServer struct {
}

func (UnimplementedPromisesServer) ReadPromise(context.Context, *ReadPromiseRequest) (*ReadPromiseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadPromise not implemented")
}
func (UnimplementedPromisesServer) SearchPromises(context.Context, *SearchPromisesRequest) (*SearchPromisesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchPromises not implemented")
}
func (UnimplementedPromisesServer) CreatePromise(context.Context, *CreatePromiseRequest) (*CreatePromiseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePromise not implemented")
}
func (UnimplementedPromisesServer) CreatePromiseAndTask(context.Context, *CreatePromiseAndTaskRequest) (*CreatePromiseAndTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePromiseAndTask not implemented")
}
func (UnimplementedPromisesServer) ResolvePromise(context.Context, *ResolvePromiseRequest) (*ResolvePromiseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolvePromise not implemented")
}
func (UnimplementedPromisesServer) RejectPromise(context.Context, *RejectPromiseRequest) (*RejectPromiseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectPromise not implemented")
}
func (UnimplementedPromisesServer) CancelPromise(context.Context, *CancelPromiseRequest) (*CancelPromiseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelPromise not implemented")
}
func (UnimplementedPromisesServer) CreateCallback(context.Context, *CreateCallbackRequest) (*CreateCallbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCallback not implemented")
}
func (UnimplementedPromisesServer) CreateSubscription(context.Context, *CreateSubscriptionRequest) (*CreateSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSubscription not implemented")
}
func (UnimplementedPromisesServer) mustEmbedUnimplementedPromisesServer() {}

// UnsafePromisesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PromisesServer will
// result in compilation errors.
type UnsafePromisesServer interface {
	mustEmbedUnimplementedPromisesServer()
}

func RegisterPromisesServer(s grpc.ServiceRegistrar, srv PromisesServer) {
	s.RegisterService(&Promises_ServiceDesc, srv)
}

func _Promises_ReadPromise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPromiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromisesServer).ReadPromise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promises_ReadPromise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromisesServer).ReadPromise(ctx, req.(*ReadPromiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promises_SearchPromises_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPromisesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromisesServer).SearchPromises(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promises_SearchPromises_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromisesServer).SearchPromises(ctx, req.(*SearchPromisesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promises_CreatePromise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePromiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromisesServer).CreatePromise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promises_CreatePromise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromisesServer).CreatePromise(ctx, req.(*CreatePromiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promises_CreatePromiseAndTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePromiseAndTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromisesServer).CreatePromiseAndTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promises_CreatePromiseAndTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromisesServer).CreatePromiseAndTask(ctx, req.(*CreatePromiseAndTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promises_ResolvePromise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolvePromiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromisesServer).ResolvePromise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promises_ResolvePromise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromisesServer).ResolvePromise(ctx, req.(*ResolvePromiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promises_RejectPromise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectPromiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromisesServer).RejectPromise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promises_RejectPromise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromisesServer).RejectPromise(ctx, req.(*RejectPromiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promises_CancelPromise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPromiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromisesServer).CancelPromise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promises_CancelPromise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromisesServer).CancelPromise(ctx, req.(*CancelPromiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promises_CreateCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromisesServer).CreateCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promises_CreateCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromisesServer).CreateCallback(ctx, req.(*CreateCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promises_CreateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromisesServer).CreateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promises_CreateSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromisesServer).CreateSubscription(ctx, req.(*CreateSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Promises_ServiceDesc is the grpc.ServiceDesc for Promises service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Promises_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "promise.Promises",
	HandlerType: (*PromisesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadPromise",
			Handler:    _Promises_ReadPromise_Handler,
		},
		{
			MethodName: "SearchPromises",
			Handler:    _Promises_SearchPromises_Handler,
		},
		{
			MethodName: "CreatePromise",
			Handler:    _Promises_CreatePromise_Handler,
		},
		{
			MethodName: "CreatePromiseAndTask",
			Handler:    _Promises_CreatePromiseAndTask_Handler,
		},
		{
			MethodName: "ResolvePromise",
			Handler:    _Promises_ResolvePromise_Handler,
		},
		{
			MethodName: "RejectPromise",
			Handler:    _Promises_RejectPromise_Handler,
		},
		{
			MethodName: "CancelPromise",
			Handler:    _Promises_CancelPromise_Handler,
		},
		{
			MethodName: "CreateCallback",
			Handler:    _Promises_CreateCallback_Handler,
		},
		{
			MethodName: "CreateSubscription",
			Handler:    _Promises_CreateSubscription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/app/subsystems/api/grpc/pb/promise.proto",
}
