// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: internal/app/subsystems/api/grpc/pb/schedule_t.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Schedule struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Cron           string                 `protobuf:"bytes,3,opt,name=cron,proto3" json:"cron,omitempty"`
	Tags           map[string]string      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PromiseId      string                 `protobuf:"bytes,5,opt,name=promiseId,proto3" json:"promiseId,omitempty"`
	PromiseTimeout int64                  `protobuf:"varint,6,opt,name=promiseTimeout,proto3" json:"promiseTimeout,omitempty"`
	PromiseParam   *Value                 `protobuf:"bytes,7,opt,name=promiseParam,proto3" json:"promiseParam,omitempty"`
	PromiseTags    map[string]string      `protobuf:"bytes,8,rep,name=promiseTags,proto3" json:"promiseTags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IdempotencyKey string                 `protobuf:"bytes,9,opt,name=idempotencyKey,proto3" json:"idempotencyKey,omitempty"`
	LastRunTime    int64                  `protobuf:"varint,10,opt,name=lastRunTime,proto3" json:"lastRunTime,omitempty"`
	NextRunTime    int64                  `protobuf:"varint,11,opt,name=nextRunTime,proto3" json:"nextRunTime,omitempty"`
	CreatedOn      int64                  `protobuf:"varint,12,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_rawDescGZIP(), []int{0}
}

func (x *Schedule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Schedule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Schedule) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *Schedule) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Schedule) GetPromiseId() string {
	if x != nil {
		return x.PromiseId
	}
	return ""
}

func (x *Schedule) GetPromiseTimeout() int64 {
	if x != nil {
		return x.PromiseTimeout
	}
	return 0
}

func (x *Schedule) GetPromiseParam() *Value {
	if x != nil {
		return x.PromiseParam
	}
	return nil
}

func (x *Schedule) GetPromiseTags() map[string]string {
	if x != nil {
		return x.PromiseTags
	}
	return nil
}

func (x *Schedule) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Schedule) GetLastRunTime() int64 {
	if x != nil {
		return x.LastRunTime
	}
	return 0
}

func (x *Schedule) GetNextRunTime() int64 {
	if x != nil {
		return x.NextRunTime
	}
	return 0
}

func (x *Schedule) GetCreatedOn() int64 {
	if x != nil {
		return x.CreatedOn
	}
	return 0
}

var File_internal_app_subsystems_api_grpc_pb_schedule_t_proto protoreflect.FileDescriptor

const file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_rawDesc = "" +
	"\n" +
	"4internal/app/subsystems/api/grpc/pb/schedule_t.proto\x12\n" +
	"schedule_t\x1a3internal/app/subsystems/api/grpc/pb/promise_t.proto\"\xcc\x04\n" +
	"\bSchedule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04cron\x18\x03 \x01(\tR\x04cron\x122\n" +
	"\x04tags\x18\x04 \x03(\v2\x1e.schedule_t.Schedule.TagsEntryR\x04tags\x12\x1c\n" +
	"\tpromiseId\x18\x05 \x01(\tR\tpromiseId\x12&\n" +
	"\x0epromiseTimeout\x18\x06 \x01(\x03R\x0epromiseTimeout\x124\n" +
	"\fpromiseParam\x18\a \x01(\v2\x10.promise_t.ValueR\fpromiseParam\x12G\n" +
	"\vpromiseTags\x18\b \x03(\v2%.schedule_t.Schedule.PromiseTagsEntryR\vpromiseTags\x12&\n" +
	"\x0eidempotencyKey\x18\t \x01(\tR\x0eidempotencyKey\x12 \n" +
	"\vlastRunTime\x18\n" +
	" \x01(\x03R\vlastRunTime\x12 \n" +
	"\vnextRunTime\x18\v \x01(\x03R\vnextRunTime\x12\x1c\n" +
	"\tcreatedOn\x18\f \x01(\x03R\tcreatedOn\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10PromiseTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BDZBgithub.com/resonatehq/resonate/internal/app/subsystems/api/grpc/pbb\x06proto3"

var (
	file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_rawDescOnce sync.Once
	file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_rawDescData []byte
)

func file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_rawDescGZIP() []byte {
	file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_rawDescOnce.Do(func() {
		file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_rawDesc), len(file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_rawDesc)))
	})
	return file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_rawDescData
}

var file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_goTypes = []any{
	(*Schedule)(nil), // 0: schedule_t.Schedule
	nil,              // 1: schedule_t.Schedule.TagsEntry
	nil,              // 2: schedule_t.Schedule.PromiseTagsEntry
	(*Value)(nil),    // 3: promise_t.Value
}
var file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_depIdxs = []int32{
	1, // 0: schedule_t.Schedule.tags:type_name -> schedule_t.Schedule.TagsEntry
	3, // 1: schedule_t.Schedule.promiseParam:type_name -> promise_t.Value
	2, // 2: schedule_t.Schedule.promiseTags:type_name -> schedule_t.Schedule.PromiseTagsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_init() }
func file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_init() {
	if File_internal_app_subsystems_api_grpc_pb_schedule_t_proto != nil {
		return
	}
	file_internal_app_subsystems_api_grpc_pb_promise_t_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_rawDesc), len(file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_goTypes,
		DependencyIndexes: file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_depIdxs,
		MessageInfos:      file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_msgTypes,
	}.Build()
	File_internal_app_subsystems_api_grpc_pb_schedule_t_proto = out.File
	file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_goTypes = nil
	file_internal_app_subsystems_api_grpc_pb_schedule_t_proto_depIdxs = nil
}
