name: Remove Stale Branches

permissions:
  contents: write
  actions: read
  pull-requests: read

on:
  schedule:
    - cron: "0 0 * * *" # Everday at midnight
  workflow_dispatch:

jobs:
  run:
    name: Remove Stale Branches
    runs-on: ubuntu-latest
    steps:
      - uses: fpicalausa/remove-stale-branches@v2.4.0
