[package]
name = "resonate-server-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Resonate server: durable state in PostgreSQL."

[features]
concurrency-stress = []

[dependencies]
resonate-sql = { path = "../resonate-sql" }
resonate-core = { path = "../resonate-core" }
resonate-plugin = { path = "../resonate-plugin" }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
validator = { workspace = true }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync", "macros"] }
tracing = "0.1"
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio-rustls", "macros", "migrate", "postgres"] }

[dev-dependencies]
base64 = "0.22"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
