-------------------- MODULE AbstractCheck --------------------
(* GENERATED by mkcheck.py -- do not edit. *)
EXTENDS Abstract

I == INSTANCE Invariants

inv_well_formed_promise_created_at_lte_timeout_at ==
    I!well_formed_promise_created_at_lte_timeout_at

inv_well_formed_promise_pending_created_before_deadline ==
    I!well_formed_promise_pending_created_before_deadline

inv_well_formed_promise_settled_at_lte_timeout_at ==
    I!well_formed_promise_settled_at_lte_timeout_at

inv_well_formed_promise_created_at_lte_settled_at ==
    I!well_formed_promise_created_at_lte_settled_at

inv_well_formed_promise_settled_at_iff_not_pending ==
    I!well_formed_promise_settled_at_iff_not_pending

inv_well_formed_promise_pending_has_no_value ==
    I!well_formed_promise_pending_has_no_value

inv_well_formed_promise_deadline_verdict_matches_timer_tag ==
    I!well_formed_promise_deadline_verdict_matches_timer_tag

inv_well_formed_promise_deadline_settlement_has_no_value ==
    I!well_formed_promise_deadline_settlement_has_no_value

inv_well_formed_promise_timer_not_targeted ==
    I!well_formed_promise_timer_not_targeted

inv_well_formed_promise_timedout_is_server_owned ==
    I!well_formed_promise_timedout_is_server_owned

inv_well_formed_promise_obligations_require_external ==
    I!well_formed_promise_obligations_require_external

inv_well_formed_promise_awaiter_is_not_self ==
    I!well_formed_promise_awaiter_is_not_self

inv_well_formed_promise_created_at_lte_now ==
    I!well_formed_promise_created_at_lte_now

inv_well_formed_promise_settled_at_lte_now ==
    I!well_formed_promise_settled_at_lte_now

inv_well_formed_task_acquired_iff_has_pid ==
    I!well_formed_task_acquired_iff_has_pid

inv_well_formed_task_acquired_iff_has_ttl ==
    I!well_formed_task_acquired_iff_has_ttl

inv_well_formed_task_acquired_iff_has_lease_timeout_at ==
    I!well_formed_task_acquired_iff_has_lease_timeout_at

inv_well_formed_task_pending_iff_has_retry_timeout_at ==
    I!well_formed_task_pending_iff_has_retry_timeout_at

inv_well_formed_task_fulfilled_is_cleared ==
    I!well_formed_task_fulfilled_is_cleared

inv_well_formed_task_suspended_is_cleared ==
    I!well_formed_task_suspended_is_cleared

inv_well_formed_task_halted_is_cleared ==
    I!well_formed_task_halted_is_cleared

inv_well_formed_task_suspended_has_no_resumes ==
    I!well_formed_task_suspended_has_no_resumes

inv_well_formed_task_acquired_version_positive ==
    I!well_formed_task_acquired_version_positive

inv_well_formed_store_outbox_keys_unique ==
    I!well_formed_store_outbox_keys_unique

inv_consistent_task_iff_targeted_promise ==
    I!consistent_task_iff_targeted_promise

inv_consistent_settled_promise_has_fulfilled_task ==
    I!consistent_settled_promise_has_fulfilled_task

inv_consistent_callback_awaiter_is_targeted ==
    I!consistent_callback_awaiter_is_targeted

inv_consistent_outbox_execute_names_existing_task ==
    I!consistent_outbox_execute_names_existing_task

inv_consistent_outbox_never_ahead ==
    I!consistent_outbox_never_ahead

inv_consistent_outbox_execute_address_is_target_tag ==
    I!consistent_outbox_execute_address_is_target_tag

inv_consistent_outbox_unblock_names_settled_promise ==
    I!consistent_outbox_unblock_names_settled_promise

inv_consistent_suspended_task_holds_rung ==
    I!consistent_suspended_task_holds_rung

inv_consistent_settled_task_promise_settled ==
    I!consistent_settled_task_promise_settled

inv_well_formed_task_ttl_positive ==
    I!well_formed_task_ttl_positive

inv_well_formed_promise_target_is_nonempty ==
    I!well_formed_promise_target_is_nonempty

inv_well_formed_promise_delay_before_deadline ==
    I!well_formed_promise_delay_before_deadline

prop_preserved_promise_birth_fields_immutable ==
    [][I!preserved_promise_birth_fields_immutable]_vars

prop_preserved_settled_promise_record ==
    [][I!preserved_settled_promise_record]_vars

prop_monotone_promise_set_grows ==
    [][I!monotone_promise_set_grows]_vars

prop_monotone_task_set_grows ==
    [][I!monotone_task_set_grows]_vars

prop_monotone_task_version_increases_only_on_acquisition ==
    [][I!monotone_task_version_increases_only_on_acquisition]_vars

prop_preserved_fulfilled_task ==
    [][I!preserved_fulfilled_task]_vars

prop_preserved_no_dead_dispatch ==
    [][I!preserved_no_dead_dispatch]_vars

prop_preserved_execute_only_for_live_task ==
    [][I!preserved_execute_only_for_live_task]_vars

prop_preserved_promise_state_frozen_once_settled ==
    [][I!preserved_promise_state_frozen_once_settled]_vars

prop_preserved_promise_settlement_is_one_way ==
    [][I!preserved_promise_settlement_is_one_way]_vars

prop_consistent_promise_settled_at_moves_with_state ==
    [][I!consistent_promise_settled_at_moves_with_state]_vars

prop_preserved_promise_value_until_settlement ==
    [][I!preserved_promise_value_until_settlement]_vars

prop_monotone_promise_callbacks_grow_while_pending ==
    [][I!monotone_promise_callbacks_grow_while_pending]_vars

prop_monotone_promise_callbacks_shrink_once_settled ==
    [][I!monotone_promise_callbacks_shrink_once_settled]_vars

prop_monotone_promise_listeners_grow_while_pending ==
    [][I!monotone_promise_listeners_grow_while_pending]_vars

prop_monotone_promise_listeners_shrink_once_settled ==
    [][I!monotone_promise_listeners_shrink_once_settled]_vars

prop_consistent_promise_state_edge_admissible ==
    [][I!consistent_promise_state_edge_admissible]_vars

prop_consistent_task_state_edge_admissible ==
    [][I!consistent_task_state_edge_admissible]_vars

prop_preserved_task_acquisition_only_from_pending ==
    [][I!preserved_task_acquisition_only_from_pending]_vars

prop_preserved_task_suspension_only_from_acquired ==
    [][I!preserved_task_suspension_only_from_acquired]_vars

prop_preserved_task_halted_only_reenters_via_pending ==
    [][I!preserved_task_halted_only_reenters_via_pending]_vars

prop_consistent_settlement_fulfils_task ==
    [][I!consistent_settlement_fulfils_task]_vars

prop_consistent_task_fulfilment_needs_settlement ==
    [][I!consistent_task_fulfilment_needs_settlement]_vars

prop_consistent_obligation_discharge_requires_settled ==
    [][I!consistent_obligation_discharge_requires_settled]_vars

prop_consistent_callback_consumption_resumes_awaiter ==
    [][I!consistent_callback_consumption_resumes_awaiter]_vars

prop_consistent_listener_consumption_enqueues_unblock ==
    [][I!consistent_listener_consumption_enqueues_unblock]_vars

prop_consistent_wake_follows_callback_consumption ==
    [][I!consistent_wake_follows_callback_consumption]_vars

prop_consistent_suspension_registers_callback ==
    [][I!consistent_suspension_registers_callback]_vars

prop_consistent_task_birth_couples_promise_birth ==
    [][I!consistent_task_birth_couples_promise_birth]_vars

prop_monotone_outbox_keys_never_disappear ==
    [][I!monotone_outbox_keys_never_disappear]_vars

prop_consistent_new_execute_matches_task_and_target ==
    [][I!consistent_new_execute_matches_task_and_target]_vars

prop_consistent_new_unblock_carries_stored_record ==
    [][I!consistent_new_unblock_carries_stored_record]_vars

prop_consistent_new_unblock_discharges_its_listener ==
    [][I!consistent_new_unblock_discharges_its_listener]_vars

prop_consistent_task_birth_state ==
    [][I!consistent_task_birth_state]_vars

prop_consistent_task_lease_released_atomically ==
    [][I!consistent_task_lease_released_atomically]_vars

prop_preserved_task_lease_holder_stable ==
    [][I!preserved_task_lease_holder_stable]_vars

prop_consistent_task_lease_fields_move_together ==
    [][I!consistent_task_lease_fields_move_together]_vars

prop_monotone_task_resumes_grow_or_clear ==
    [][I!monotone_task_resumes_grow_or_clear]_vars

prop_consistent_task_resumes_cleared_only_on_dispatch_or_park ==
    [][I!consistent_task_resumes_cleared_only_on_dispatch_or_park]_vars

prop_consistent_task_acquisition_is_atomic ==
    [][I!consistent_task_acquisition_is_atomic]_vars

prop_consistent_task_lease_deadline_is_now_plus_ttl ==
    [][I!consistent_task_lease_deadline_is_now_plus_ttl]_vars

prop_consistent_task_pending_entry_arms_retry ==
    [][I!consistent_task_pending_entry_arms_retry]_vars

prop_consistent_task_retry_rearm_only_when_due ==
    [][I!consistent_task_retry_rearm_only_when_due]_vars

prop_consistent_task_wake_records_resume ==
    [][I!consistent_task_wake_records_resume]_vars

prop_consistent_promise_settlement_stamp ==
    [][I!consistent_promise_settlement_stamp]_vars

prop_preserved_timedout_is_server_owned ==
    [][I!preserved_timedout_is_server_owned]_vars

prop_consistent_new_promise_born_clean ==
    [][I!consistent_new_promise_born_clean]_vars

prop_monotone_task_retry_rearm_advances ==
    [][I!monotone_task_retry_rearm_advances]_vars

===============================================================================
