openapi: 3.0.0
info:
  title: Tasks API
  description: Manage Tasks
  version: 1.0.0
paths:
  /tasks/claim:
    post:
      tags:
        - Tasks
      summary: Claim a task
      operationId: claimTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClaimTaskReq"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Promise"
        "409":
          description: Task already claimed

  /tasks/complete:
    post:
      tags:
        - Tasks
      summary: Complete a task
      operationId: completeTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CompleteTaskReq"
      responses:
        "200":
          description: successful operation
        "409":
          description: Task already completed

components:
  #parameters:
  schemas:
    Promise:
      type: object
      required:
        - id
        - state
        - timeout
        - param
        - value
        - tags
      properties:
        id:
          type: string
        state:
          $ref: "#/components/schemas/PromiseState"
        param:
          $ref: "#/components/schemas/PromiseValue"
        value:
          $ref: "#/components/schemas/PromiseValue"
        timeout:
          type: integer
          format: int64
        idempotencyKeyForCreate:
          type: string
          readOnly: true
        idempotencyKeyForComplete:
          type: string
          readOnly: true
        tags:
          type: object
          additionalProperties:
            type: string
        createdOn:
          type: integer
          readOnly: true
        completedOn:
          type: integer
          readOnly: true

    PromiseState:
      type: string
      enum:
        - PENDING
        - RESOLVED
        - REJECTED
        - REJECTED_CANCELED
        - REJECTED_TIMEDOUT

    PromiseStateComplete:
      type: string
      enum:
        - RESOLVED
        - REJECTED

    PromiseValue:
      type: object
      required:
        - headers
      properties:
        headers:
          type: object
          additionalProperties:
            type: string
        data:
          type: string

    ClaimTaskReq:
      type: object
      properties:
        taskId:
          type: string
          description: The ID of the task to claim
        counter:
          type: integer
          description: The counter of the task to claim
        processId:
          type: string
        executionId:
          type: string
        expiryInMilliseconds:
          type: integer
          format: int64
      required:
        - taskId
        - counter
        - processId
        - executionId
        - expiryInMilliseconds

    CompleteTaskReq:
      type: object
      properties:
        taskId:
          type: string
          description: The ID of the task to complete
        counter:
          type: integer
          description: The counter of the task to claim
        executionId:
          type: string
        state:
          $ref: "#/components/schemas/PromiseStateComplete"
        value:
          $ref: "#/components/schemas/PromiseValue"
      required:
        - taskId
        - counter
        - executionId
        - state
        - value
