name: CD

on:
  push:
    paths:
      - "cmd/**"
      - "internal/**"
      - "pkg/**"
      - "test/**"
      - "Dockerfile"
      - "go.mod"
      - "go.sum"
      - "main.go"
      - "Makefile"
    branches: 
    - main 
  
  pull_request: # remove just for testing
    branches:
    - main

permissions:
  contents: read
  id-token: write

jobs:
  release-linux-binary:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: 1.21
    - name: Install cross-compiler for linux/arm64
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu
    - name: Build for both amd64 and arm64
      run: |
        GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -o ./bin/linux-x86_64/ ./...
        CC=aarch64-linux-gnu-gcc GOOS=linux GOARCH=arm64 CGO_ENABLED=1 go build -o ./bin/linux-aarch64/ ./...
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - id: upload-linux-x86_64
      uses: google-github-actions/upload-cloud-storage@v1
      with:
        path: ./bin/linux-x86_64/resonate
        destination: resonate-release/linux-x86_64
    - id: upload-linux-aarch64
      uses: google-github-actions/upload-cloud-storage@v1
      with:
        path: ./bin/linux-aarch64/resonate
        destination: resonate-release/linux-aarch64
  
  release-darwin-binary:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: 1.21
    - name: Build for both amd64 and arm64
      run: |
        GOOS=darwin GOARCH=amd64 CGO_ENABLED=1 go build -o ./bin/darwin-x86_64/ ./... 
        GOOS=darwin GOARCH=arm64 CGO_ENABLED=1 go build -o ./bin/darwin-aarch64/ ./...
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - id: upload-darwin-x86_64 
      uses: google-github-actions/upload-cloud-storage@v1
      with:
        path: ./bin/darwin-x86_64/resonate
        destination: resonate-release/darwin-x86_64
    - id: upload-darwin-aarch64 
      uses: google-github-actions/upload-cloud-storage@v1
      with:
        path: ./bin/darwin-aarch64/resonate
        destination: resonate-release/darwin-aarch64
