name: CI/CD 

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read
  id-token: write
  
jobs:

  ci:
    uses: ./.github/workflows/ci.yaml

  cd:
    needs: ci     
    uses: ./.github/workflows/cd.yaml