name: OpenAPI Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write # push to gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Generate API documentation with Redocly
        run: redocly build-docs api/openapi.yml --output api/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./api
