name: Publish GitHub Release

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag
        id: create_tag
        run: |
          tag_name="v$(date +'%Y.%m.%d')"
          echo "::set-output name=tag_name::$tag_name"
    outputs:
      tag_name: ${{ steps.create_tag.outputs.tag_name }}
      
  build:
    runs-on: ubuntu-latest
    needs: [create_tag]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Create Tag
        id: create_tag
        run: |
          tag_name="v$(date +'%Y.%m.%d')"
          echo "::set-output name=tag_name::$tag_name"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: Release.txt
          name: Resonate ${{ needs.create_tag.outputs.tag_name }}
          tag_name: ${{ needs.create_tag.outputs.tag_name }}
          generate_release_notes: true
          make_latest: true
          
  release-linux-artifact:
    runs-on: ubuntu-latest
    needs: [create_tag, build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Install cross-compiler for linux/arm64
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
      - name: Build for both amd64 and arm64
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -o ./bin/linux-x86_64/ ./...
          CC=aarch64-linux-gnu-gcc GOOS=linux GOARCH=arm64 CGO_ENABLED=1 go build -o ./bin/linux-aarch64/ ./...
          chmod +x ./bin/linux-x86_64/resonate
          chmod +x ./bin/linux-aarch64/resonate
          tar -czvf resonate_linux_x86_64.tar.gz ./bin/linux-x86_64/resonate
          sha256sum resonate_linux_x86_64.tar.gz > resonate_linux_x86_64.tar.gz.sha256
          tar -czvf resonate_linux_aarch64.tar.gz ./bin/linux-aarch64/resonate
          sha256sum resonate_linux_aarch64.tar.gz > resonate_linux_aarch64.tar.gz.sha256
      - name: Upload Artifacts
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ needs.create_tag.outputs.tag_name }} resonate_linux_x86_64.tar.gz --clobber
          gh release upload ${{ needs.create_tag.outputs.tag_name }} resonate_linux_x86_64.tar.gz.sha256 --clobber
          gh release upload ${{ needs.create_tag.outputs.tag_name }} resonate_linux_aarch64.tar.gz --clobber
          gh release upload ${{ needs.create_tag.outputs.tag_name }} resonate_linux_aarch64.tar.gz.sha256 --clobber

  release-darwin-artifact:
    runs-on: macos-latest
    needs: [create_tag, build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Build for both amd64 and arm64
        run: |
          GOOS=darwin GOARCH=amd64 CGO_ENABLED=1 go build -o ./bin/darwin-x86_64/ ./... 
          GOOS=darwin GOARCH=arm64 CGO_ENABLED=1 go build -o ./bin/darwin-aarch64/ ./...
          chmod +x ./bin/darwin-x86_64/resonate
          chmod +x ./bin/darwin-aarch64/resonate
          tar -czvf resonate_darwin_x86_64.tar.gz ./bin/darwin-x86_64/resonate
          shasum -a 256 resonate_darwin_x86_64.tar.gz > resonate_darwin_x86_64.tar.gz.sha256
          tar -czvf resonate_darwin_aarch64.tar.gz ./bin/darwin-aarch64/resonate
          shasum -a 256 resonate_darwin_aarch64.tar.gz > resonate_darwin_aarch64.tar.gz.sha256
      - name: Upload Artifacts
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ needs.create_tag.outputs.tag_name }} resonate_darwin_x86_64.tar.gz --clobber
          gh release upload ${{ needs.create_tag.outputs.tag_name }} resonate_darwin_x86_64.tar.gz.sha256 --clobber
          gh release upload ${{ needs.create_tag.outputs.tag_name }} resonate_darwin_aarch64.tar.gz --clobber
          gh release upload ${{ needs.create_tag.outputs.tag_name }} resonate_darwin_aarch64.tar.gz.sha256 --clobber

